proyecto/app_crud/urls.py
from django.urls import path
from . views import listaEmpleados,crear_empleado,eliminar_empleado
from . import views


urlpatterns = [
    path('', listaEmpleados.as_view(), name='listaEmpleados'),


    #path('detalles_empleado/<str:id>/', views.detalles_empleado, name='detalles_empleado'),
    path('crear_empleado/', crear_empleado.as_view(), name='crear_empleado'),
    path('editar-empleado/<int:pk>/', views.editar_empleado.as_view(), name='editar-empleado'),
    path('eliminar-empleado/<int:pk>/', views.eliminar_empleado.as_view(), name='eliminar-empleado'),
    
    
    path('upload/', views.upload_file, name='upload_file'),
    path('success/', views.success, name='success'),
    
    
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_crud.urls')),
]

proyecto/app_crud/models.py
from django.db import models

# Create your models here.

generos = (
    ("Masculino", "Masculino"),
    ("Femenino", "Femenino"),
    ("Otro", "Otro"),
)


class Empleado(models.Model):
    Nombre = models.CharField(max_length=150)
    Apellido = models.CharField(max_length=150)
    Email = models.EmailField(max_length=150)
    Edad = models.IntegerField()
    Generos = models.CharField(max_length=100, choices=generos)
    Salario = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    Fecha_inicial = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    Fecha_actualizada = models.DateTimeField(auto_now_add=False, auto_now=True)


    
    class Meta:
        db_table = "empleados"
        ordering = ['-Fecha_inicial']

proyecto/app_crud/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()
    
    

    
    
    
    
    
    
    
    

proyecto/app_crud/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
#from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . models import Empleado
from django.urls import reverse_lazy
#from django.contrib.auth.mixins import LoginRequiredMixin
import pandas as pd
from django.http import JsonResponse
import os
from django.core.files.uploadedfile import SimpleUploadedFile
import uuid
import logging





from django.shortcuts import  redirect
from . forms import UploadFileForm

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            df = pd.read_excel(file)

            for _, row in df.iterrows():
                Empleado.objects.create(
                   
                    # Agrega más columnas según tu modelo
                   
                    Nombre = row['Nombre'],
                    Apellido = row['Apellido'],
                    Edad = row['Edad'],
                    Email = row['Email'],
                    Generos = row['Sexo'],
                    Salario = row['Salario'],
                    
                    
                )
            return redirect('success')
    else:
        form = UploadFileForm()
    return render(request, 'app_crud/upload.html', {'form': form})



def success(request):
    return render(request, 'app_crud/success.html')










class listaEmpleados(ListView):
    model = Empleado
    context_object_name = 'object_empleados'
    
    
    
"""  def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_empleados'] = context['object_empleados'].filter(usuario=self.request.user) 
        context['count'] = context['object_empleados'].filter(completo=False).count()
        
        valor_buscado = self.request.GET.get('area_buscar') or ''
        if valor_buscado:
            context['object_empleados'] = context['object_empleados'].filter(titulo__icontains=valor_buscado)
        context['valor_buscado'] = valor_buscado
        return context  """
   

""" class detalles_empleado(DetailView):
    model = Empleado
    context_object_name = 'object_detalle'
    template_name = 'app_crud/detalles.html'  """
    

""" def detalles_empleado(request, id):
    try:
        empleado = Empleado.objects.get(id=id)
        data = {"empleado": empleado}
        return render(request, "app_crud/detalles.html", data)
    except Empleado.DoesNotExist:
        error_message = f"no existe ningún registro para la busqueda id: {id}"
        return render(request, "app_crud/empleado_list.html", {"error_message": error_message}) """


class crear_empleado(CreateView):
    model = Empleado
    fields = '__all__'
    success_url = reverse_lazy('listaEmpleados')
    
class editar_empleado(UpdateView):
    model = Empleado
    fields = '__all__'
    success_url = reverse_lazy('listaEmpleados')
    
class eliminar_empleado(DeleteView):
    model = Empleado
    context_object_name = 'deleteEmpleados'
    success_url = reverse_lazy('listaEmpleados')
    
    
def view_form_carga_masiva(request):
    return render(request, 'app_crud/form_carga_masiva.html')

""" 
def cargar_archivo(request):
    try:
        if request.method == 'POST':
            archivo_xlsx = request.FILES['archivo_xlsx']
            if archivo_xlsx.name.endswith('.xlsx'):
                df = pd.read_excel(archivo_xlsx, header=0)

                for _, row in df.iterrows():
                    Nombre = row['Nombre']
                    Apellido = row['Apellido']
                    Edad = row['Edad']
                    Email = row['Email']
                    Generos = row['Sexo']
                    Salario = row['Salario']

                    empleado, creado = Empleado.objects.update_or_create(
                        Email=Email,
                        defaults={
                            'Nombre': Nombre,
                            'Apellido': Apellido,
                            'Edad': Edad,
                            'Email': Email,
                            'Generos': Generos,
                            'Salario': Salario,
                            
                        }
                    )

                return JsonResponse({'status_server': 'success', 'message': 'Los datos se importaron correctamente.'})
            else:
                return JsonResponse({'status_server': 'error', 'message': 'El archivo debe ser un archivo de Excel válido.'})
        else:
            return JsonResponse({'status_server': 'error', 'message': 'Método HTTP no válido.'})

    except Exception as e:
        logging.error("Error al cargar el archivo: %s", str(e))
        return JsonResponse({'status_server': 'error', 'message': f'Error al cargar el archivo: {str(e)}'})


# Genera un nombre único para el archivo utilizando UUID y conserva la extensión.
def generate_unique_filename(file):
    extension = os.path.splitext(file.name)[1]
    unique_name = f'{uuid.uuid4()}{extension}'
    return SimpleUploadedFile(unique_name, file.read())
    
 """
 
def cargar_archivo(request):
    if request.method == 'POST':
        archivo_xlsx = request.FILES.get('archivo_xlsx')
        if archivo_xlsx and archivo_xlsx.name.endswith('.xlsx'):
            try:
                df = pd.read_excel(archivo_xlsx, header=0)
                empleados = []
                for _, row in df.iterrows():
                    empleado = Empleado(
                        Nombre=row['Nombre'],
                        Apellido=row['Apellido'],
                        Edad=row['Edad'],
                        Email=row['Email'],
                        Generos=row['Sexo'],
                        Salario=row['Salario']
                    )
                    empleados.append(empleado)
                Empleado.objects.bulk_create(empleados, ignore_conflicts=True)
                return JsonResponse({'status_server': 'success', 'message': 'Los datos se importaron correctamente.'})
            except Exception as e:
                logging.error("Error al cargar el archivo: %s", str(e))
                return JsonResponse({'status_server': 'error', 'message': f'Error al cargar el archivo: {str(e)}'})
        else:
            return JsonResponse({'status_server': 'error', 'message': 'El archivo debe ser un archivo de Excel válido.'})
    return render(request, 'listaEmpleados.html')

proyecto/app_crud/templates/app_crud/empleado_confirm_delete.html
{% extends 'app_crud/principal.html' %}

{% block content %}


<a href="{% url 'listaEmpleados' %}" class="volver_delete">volver</a>
<div class="contend_delete">

<form action="" method="post">
    {% csrf_token %}

    <p>Vas a Eliminar al Empleado: "{{deleteEmpleados.Nombre}}"</p>
    <input type="submit" value="Eliminar" class="btn_form">

</form>

</div>

{% endblock content %}

proyecto/app_crud/templates/app_crud/empleado_form.html
{% extends 'app_crud/principal.html' %}

{% block content %}
<div class="contenedor_fomulario">
    <a href="{% url 'listaEmpleados' %}" class="volver">volver</a>
<div class="border_form">
<h1>Registro de Empleados</h1>


<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Enviar" class="btn_form">

</form>
</div>
</div>
{% endblock content %}

proyecto/app_crud/templates/app_crud/empleado_list.html
{% extends 'app_crud/principal.html' %}

{% block content %}

<div class="conten_titulo">
<h1 class="titulo_lista">Lista de Empleados</h1>

<a href="{% url 'upload_file' %}" class="btn_modal">Cargar Masivos</a>


</div>
<div class="conten_busqueda">
<a href="{% url 'crear_empleado' %}" class="registrar">Registrar Empleado</a>


<!-- <form action="" method="get" class="form_buscar">

    
    <input type="text" name="area_buscar" placeholder="Buscar" value="{{valor_buscado}}" class="txt_buscar">
    <input type="submit" value="buscar" class="btn_buscar">

</form> -->


</div>

<table border>
    <tr>
        
    </tr>

    {% for Empleado in object_empleados %}

    <tr>
        <td>{{Empleado.Nombre}}</td>
        <td>{{Empleado.Apellido}}</td>
        <td>{{Empleado.Email}}</td>
        <td>{{Empleado.Edad}}</td>
        <td>{{Empleado.Generos}}</td>
        <td>{{Empleado.Salario}}</td>


      
        <td><a href="{% url 'editar-empleado' Empleado.id %}" id="btn_editar">editar</a><a id="btn_eliminar" href="{% url 'eliminar-empleado' Empleado.id %}">eliminar</a></td>
        
    </tr>

    {% empty %}
    <h3>no hay elementos en esta lista </h3>

    {%endfor%}

   
   
</table>




{% endblock content %}

proyecto/app_crud/templates/app_crud/principal.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>

        
        body{
            background-color: #c2e4ee;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            padding-top: 30px;
        }

        .container{
            min-width: 550px;
            max-width: 1250px;
            margin: auto;
            background-color: #b4ee8e;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow:  2px 2px 13px -4px rgba(0,0,0,0.21);
            
        }

        /* stylos de empleado_list */
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #aaa7a7;
          text-align: left;
          padding: 8px;
          
        }
        td{
            text-align: center;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
        
        
        
        .modal1::backdrop{
            background-color: rgba(0, 0, 0, 0.5);
        }

        #btn_editar{
            background-color: aqua;
            color: rgb(36, 35, 35);
            padding: 5px 2rem 5px 2rem;
            text-decoration: none;
            border-radius: 10px 0 0 10px;
        }
        #btn_editar:hover{
            background-color: rgba(7, 168, 168, 0.945);
        }
        #btn_eliminar{
            background-color: rgb(255, 0, 55);
            color: rgb(36, 35, 35);
            padding: 5px 1.5rem 5px 1.5rem;
            text-decoration: none;
            border-radius: 0 10px 10px 0;

        }
        #btn_eliminar:hover{
            background-color: rgb(150, 4, 36);
        }

        .conten_busqueda{
            display: flex;
            justify-content: space-between;
        }
     
        .conten_titulo{
            display: flex;
            justify-content: space-between;
            padding: 0 50px 0 50px;
            background-color: #1ba7b9;

        } 
        .btn_modal{
            height: 2rem;
            margin-top: 18px;
            cursor: pointer;
            padding: 0 10px 0 10px;
            font-weight: 800;
            font-size: small;
            border-radius: 10px;
            background-color: #77db34;
            text-decoration: none;
            color: rgb(36, 35, 35);
        }
        .btn_modal:hover{
            background-color: #a4e07b;
            
        }

        .registrar{
            padding: 5px 1.5rem 5px 1.5rem;
            background-color: #77d836;
            margin: 10px;
            border-radius: 10px;
            text-decoration: none;
            color: rgb(36, 35, 35);
            
        }
        .registrar:hover{
            background-color: #368105;
            
        }
        .btn_buscar{
            border: none;
            background-color: #1ba7b9;
            margin-right: 7px;
            cursor: pointer;
            border-radius: 3px;
            padding: 3px 10px 3px 10px  ;

        }
        .btn_buscar:hover{
            background-color: #44dcf0;
            
        }
        .txt_buscar{
            border: none;
            padding: 3px 10px 3px 10px  ;
            

           
        }
        .form_buscar{
            display: flex;
            justify-content: center;
            align-items: center;
            margin-right: 100px;
        }
        .dialog_modal{
            width: 100px;
            height: 100px;
        }
        /* ///////////////fin de empleado lista//////////////////////// */

        /* /////////////////inicio empleado form/////////////// */

        .contenedor_fomulario{
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            background-color: #1ba7b9;
            height: 90vh;

        }
        .border_form{
           
            border: 1px solid rgba(0, 0, 0, 0.26);
            box-shadow:  2px 2px 13px -4px rgb(0, 0, 0);
            background-color: #e0f7e0;
            padding: 2rem;
            display: flex;
            justify-content: space-between;
            
            flex-direction: column;
            border-radius: 5px;
            
        }
        .btn_form{
            margin:0 5% 10px 5%  ;
            padding: 6px 40% 6px 40%;
            border: none;
            background-color: #77db34;
        }
        .btn_form:hover{
            background-color: #4bac0b;
            cursor: pointer;
        }
        .volver{
            padding: 3px 20px 3px 20px  ;
            margin-left: -80%;
            text-decoration: none;
            background-color: #4bac0b;
            color: rgb(36, 35, 35);

        }
        .volver:hover{
            background-color: #42a103;
        }
        .volver_delete{
            padding: 3px 20px 3px 20px  ;
            text-decoration: none;
            background-color: #4bac0b;
            color: rgb(36, 35, 35); 
        }
        .volver_delete:hover{
            background-color: #398804;
        }
       
         input[type=text],input[type=email],input[type=number] , #id_Generos{
            
            margin: 0 35% 0 35%;
            padding: 6px;
            
        }
        /* /////////////////fin empleado form/////////////// */


        /* /////////////////inicio empleado delete/////////////// */

        .contend_delete{
            display: flex;
            justify-content: center;
            align-items: center;
        }   

        /* /////////////////fin empleado delete/////////////// */
        .conten_for_excel{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        


        
    </style>

</head>
<body>
    
    <div class="container">
        {% block content %}


        {% endblock content %}
    </div>


    <script>

        const modal1 = document.getElementById('mainModal1')
        
        const openModal1 = () => {
            modal1.showModal()
        }
        
        const closeModal1 = () => {
            modal1.close();
        
        }
        
        
    </script>
</body>
</html>

proyecto/app_crud/templates/app_crud/success.html
{% extends 'app_crud/principal.html' %}

{% block content %}



<h1>Documento insertado correctamente</h1>
<a href="{% url 'listaEmpleados' %}" class="volver_delete">Aceptar</a>




{% endblock content %}

proyecto/app_crud/templates/app_crud/upload.html
{% extends 'app_crud/principal.html' %}

{% block content %}



<div class="conten_for_excel">
<a href="{% url 'listaEmpleados' %}" class="volver">volver</a>
<h2>Subir archivo Excel</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"class="btn_form">Subir</button>
</form>
</div>




{% endblock content %}